---
title: "StreetLight Legacy Project FAQs"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  bookdown::word_document2:
    reference_docx: ../wordtemplate.docx
    toc: yes
    toc_depth: 1
  word_document:
    toc: yes
    toc_depth: '1'
always_allow_html: yes
urlcolor: blue
---

# FAQ

## What is this project? 
This exploratory research project aimed to determine the utility of location-based services (LBS) data for estimating park and trail use in Minnesota. LBS data was obtained from StreetLight Data, Inc. and was used to estimate park and trail use across three park systems: Department of Natural Resources state parks and trails (DNR state), Greater Minnesota regional parks and trails (Greater MN regional), and Twin Cities metropolitan regional parks and trails managed by ten implementing agencies in collaboration with the Metropolitan Council (Metro Regional). The project was funded with Legacy Partnership Research Funds from the State of Minnesota Parks and Trails Legacy Fund in collaboration with the three systems. 

## What is StreetLight Data? 
[StreetLight Data, Inc.](https://www.streetlightdata.com/) is the provider of LBS data for this project. StreetLight purchases anonymized LBS data from third-party vendors, such as [Cuebiq](https://www.cuebiq.com/) . StreetLight then processes the data, completing quality assurance and statistical tests. The project team received aggregated and anonymized travel patterns which were used for analysis. The data vendor implements data privacy methods, and it is not possible to identify individuals or individual trips through this data source or these methods. 

Broadly, LBS data is generated by GPS-enabled devices (i.e., smartphones) where users have “opted-in” to using location services. Common examples of third-party applications where users can opt in to using location services are weather, fitness, and mapping applications. Cell phone service (i.e., LTE, 3G, 4G) is not necessary for GPS functionality. StreetLight Data, Inc. uses “penetration rates” to account for incomplete adoption of GPS-enabled devices (i.e., smartphones) and users who have not opted-in to location services. StreetLight Data, Inc.’s algorithms clean the data and convert device count (i.e., sample size) into estimates of vehicles, pedestrians, and bikes which are used in this research. The LBS data provider does not explicitly measure visitors arriving by other transportation modes, but other modes (i.e., snowmobiles, boaters) may be captured and classified as either vehicle, bike, or foot visitors by the LBS data provider using their probabilistic models. 

More information about StreetLight Data, Inc.’s process can be found [on their website](https://www.streetlightdata.com/). 

## What are the benefits of using LBS/StreetLight? 
LBS data meaningfully complement existing park and trail use estimates (i.e., intercept surveys, manual counts, or physical trail counters). LBS data is available for parks and trails even when surveys or manual counts have not been performed. This research project processed data for all parks and trails eligible to receive Legacy funding, regardless of existing capacity for research or data collection. 

Additionally, LBS data has unique strengths in providing detailed spatial and temporal information. This project produced estimates for individual parks at weekly time intervals and individual trails at monthly time intervals. Data is available for January 2019 - April 2022. 

Please note that there are many park and trail research methods. Each has benefits and drawbacks; LBS data is not the appropriate tool for all research questions. 

## What can we measure? 
The LBS data used in this project includes estimated counts of vehicles, bicyclists, and pedestrians. We must apply a vehicle multiplier (average number of persons per vehicle) to convert vehicle counts to visitor counts. These counts are combined to estimate of total use at each park and trail. 

This data is available in monthly time intervals for trails and weekly time intervals for parks, allowing for detailed time series trend analyses. 

Visitor demographics are inferred based on census data. While inferred demographics are informative, they are different than intercept surveyed responses and cannot capture visitors’ lived experiences. 

The LBS data provider does not explicitly measure visitors arriving by other transportation modes, but other modes (i.e., snowmobiles, boats, equestrians, skiers) may be captured and classified as either vehicles, bikers or walkers by the LBS data provider using their probabilistic models. It cannot identify unique versus repeat visitors, nor can it measure how long visitors spend at a park or trail. Devices registered to minors (under age 18) are not included in the LBS data source. 

## How were vehicle multipliers determined? 
For Metro Regional parks, agency-level vehicle multipliers ranging between 1.71 and 2.72 were applied. State parks use a vehicle multiplier of 3.2 based on current DNR practices. We recommend 2.46 as a baseline vehicle multiplier for Greater Minnesota Regional parks. This is the average of the suburban Metro Regional agency multipliers and the DNR State park multiplier. 

## Why don’t park boundaries match official park boundaries? 
Park boundaries were edited to remove unrelated roads in order to isolate park visitors. In some cases, boundaries were expanded to include lake or river shores or amenities, such as trailheads and parking lots, that fell outside of original park boundaries. In many cases, boundaries were edited based on feedback requested throughout the project. Park and trail boundaries, in addition the number of parks and trails, remained constant over the course of this study (January 2019 – April 2022). 

## Why don't trail segments match official trail alignments?
This can happen for several reasons. Very short segments, or segments which are primarily highways, may be excluded on purpose. Otherwise, differences between trail alignments and segments are explained by OpenStreetMap data availability. In some cases, when trails run alongside roads, the best OSM match will include a longer section of road than appropriate. In other cases, the trail simply isn’t represented in OSM data. This is most common for trails still under development or for short sections or spurs. 

Trail geographies were edited based on provided shapefiles and maps available via respective agency websites, OpenStreetMap, and sources such as Minnesota Great Outdoors, AllTrails, etc. Revisions to OpenStreetMap data are beyond the scope of this project. 

## How does this project affect my park/trail? 
Data from this project is intended to supplement existing data. All partners have assisted in funding this research project, but the data from this project is not linked to funding allocation. 

## What’s next with StreetLight? 
Recent industry-wide changes to the availability of location-based services (LBS) data have forced StreetLight, and other data providers, to adopt new data sources and strategies. As of May 2022, LBS data is no longer available. Other data sources that StreetLight and other providers are migrating to are not suitable for park and trail research at this time. 

## What’s next for this project? 
We recommend using the findings from this work to guide other research until the future of LBS data is more clear. For example, these results may be used to refine existing research questions. Please view the “Recommendations and Future Work” and “Use Case” sections for more detail. At this time, the results from this project using LBS data should be viewed as a discrete research project which estimated visitation from January 2019 – April 2022 rather than part of a continuous (ongoing) research project. 
