---
title: "Reccomendations"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  bookdown::word_document2:
    reference_docx: ../wordtemplate.docx
    toc: yes
    toc_depth: 1
  word_document:
    toc: yes
    toc_depth: '1'
always_allow_html: yes
urlcolor: blue
---

# Recommendations and Future Work

## Continue collaborative projects 
The collaboration between Minnesota Legacy partners allowed us to leverage more information and resources than would have been possible if the project was internal to a single organization. We learned valuable information from partners at all three systems and combined collective knowledge to develop our methods. Collaboration to continue robust park and trail research that benefits all three Legacy partners should be considered in future work. 

We additionally learned there is no one-size-fits-all solution for park and trail research. This project aimed to develop universal approaches for park and trail analysis, but still some bespoke solutions were necessary at the unit level. Within a park system, or even within a county or city, there may be two parks with such different qualities that different techniques are needed. For example, a park accessed primarily by vehicles may require a different approach than a park with minimal parking and extensive bike access.  Due to this project’s scope, it focused on methods that apply to as many parks and trails as possible. Strategies may be improved for “edge cases,” likely with the help of park staff with detailed on-the-ground knowledge. 


## Continue exploration of novel data sources 
The findings from this study were only possible due to the adoption and exploration of novel data sources (LBS data). While exploring new data sources and methods have inherent risks and challenges, the rewards may be significant. 

However, no single data source can answer every research question about parks and trails. Like all data, LBS data has strengths and weaknesses. While it provides incredible spatial and temporal detail, it cannot provide information about visitor experiences or report real-time data, for example. Other data sources are needed to address such questions. LBS data may prove most insightful when combined with existing research methods. 

Embracing the opportunities and challenges of novel data sources and strategies can provide impactful results. Of course, new or developing data sources have the potential to change rapidly and results from using these data sources are not guaranteed. We believe that the most robust parks research program would remain adaptable, leverage a variety of data sources, and continue experimenting with and developing new approaches. 

For this project specifically, we note that industry-wide changes to the availability of LBS data have forced the data provider to discontinue providing LBS data after April 2022. While the data provider is migrating to other spatial data sources, this new data is not currently suitable for park and trail research. As such, the results from this project using LBS data should be viewed as a discrete research project which estimated visitation from January 2019 – April 2022 rather than part of a continuous (ongoing) research project. This change in availability of LBS data is emblematic of the inherit risks in using novel data sources, but the results from this project also demonstrate the rewards of exploring new data sources.  


## Connect with park staff to explore unit-level findings 
Due to this project’s scope, it was impossible to connect individually with park and trail managers, staff, or researchers at each unit. However, location-based services (LBS) data allows for highly detailed analyses and applications which may be of interest to these audiences. 

Significant on-the-ground knowledge about the park or trail of interest is often required for such analyses. Connecting park managers, staff, or researchers to this detailed data may allow for deeper analysis of individual units or generate more specific research questions. See Use Cases for additional examples of questions LBS data can answer. 


## Use findings to guide future work 
The use of LBS data in this project has suggested several avenues for future research. In most cases, future work would not be based exclusively on LBS data. While LBS data has generated insightful results in this project, it has also clarified areas where additional work is needed to supplement LBS data or answer questions that LBS data cannot. Several potential research areas are described below. 

- Interact data sources
  - LBS data showed that Minnesota’s parks and trails attract a wide range of visitors. Analysis of other data sources, such as intercept survey responses, to interact with LBS-derived visitor attributes and behavior may provide interesting results (e.g., does travel mode or distance traveled impact how visitors use parks or trails). 
- Estimate vehicle multipliers (persons per vehicle) 
  - One limitation of LBS data is that it cannot estimate the number of people in each vehicle arriving at a park. Therefore, a vehicle multiplier is needed to convert counts of vehicles to counts of people. This project has highlighted the need for high-quality vehicle multipliers: regardless of how vehicles are counted, vehicle multipliers are necessary to produce visitor counts. Vehicle multipliers are best estimated by survey data; this work indicates that vehicle multipliers may be a priority for future survey efforts. 
  - Our data show distinct use patterns across parks and trails (e.g., weekend versus weekday peaks in use, seasonal variability, high use during special events). Vehicle multipliers may be influenced by these factors. 
- Further analyze “visitation gap” and other equity questions 
  - This project produced unit-level estimates of visitor’s race and ethnicity, education, and income. These inferred demographics from LBS data may compliment work aimed at understanding of inequities and barriers to accessing parks and trails for underrepresented groups. Comparing LBS demographics to bespoke reference populations at the unit level may also be useful. 




