--- 
title: "Statewide Park and Trail Visitation"
subtitle: "A joint research project between Minnesota Department of Natural Resources, Greater Minnesota Regional Parks and Trails Commission, and Metropolitan Council | `r Sys.Date()`"
output:
  bookdown::word_document2:
    reference_docx: wordtemplate.docx
    toc: true
    toc_depth: 3
  github_document:
      toc: true
      toc_depth: 3
urlcolor: blue
always_allow_html: yes
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.pos = "H",
  out.width = "65%",
  fig.height = 4,
  fig.asp = 0.6,
  dpi = 300
)
## source basic utility functions, colors for plotting, etc
source(file.path(here::here(), "R/_load_packages.R"))
source(file.path(here(), "R/_utility_functions.R"))
source(file.path(here(), "R/_global_parameters.R"))
source(file.path(here(), "R/_streetlight_credentials_parameters.R"))
source(file.path(here(), "R/_set_aesthetics.R"))
```



```{r, child = c("INTRODUCTION.RMD", "../parks/00_PARKS.RMD", "../trails/00_TRAILS.RMD", "../visitors/00_VISITORS.RMD", "CONCLUSION.RMD", "APPENDICES.RMD")}
```
